In [46]:
# RUN THIS COMMAND ONLY IF YOU USE GOOGLE COLAB.
#from google.colab import drive
#drive.mount('/content/drive')

In [47]:
# RUN THIS COMMAND ONLY IF YOU USE GOOGLE COLAB.
%cd drive/MyDrive/TechLabs/02_Data\ Manipulation/Part\ C\ -\ Pandas

[Errno 2] No such file or directory: 'drive/MyDrive/TechLabs/02_Data Manipulation/Part C - Pandas'
/home/cakir/TechLabs/02_Data Manipulation/Part C - Pandas

/home/cakir/TechLabs/venv/lib/python3.12/site-packages/IPython/core/magics/osm.py:393: UserWarning: This is now an optional IPython functionality, using bookmarks requires you to install the `pickleshare` library.
  bkms = self.shell.db.get('bookmarks', {})

# Chapter 5 - Updating Rows and Columns - Modifying Data Within DataFrames  
### Hey Techie,   
Welcome to the fifth notebook of this Pandas tutorial series. We encourage you to take this notebook as a template to code along the instruction video, which you may find at: https://youtu.be/DCDe29sIKcE. The video deals with how to change values within Series objects and DataFrames. The underlying principles are first explained along a simple example and then applied to the real dataset we already know. At the end, as always, there are practical tasks, this time also two, to which you can write short answers as well.   

**Here you may find the Pandas documentation:** https://pandas.pydata.org/docs/reference/index.html

#### Have fun! :-)   
    
*Video length*: 40 minutes   
*Self-study time*: 40 minutes   
*Total*: **80 minutes**
<hr style="border:2px solid gray"> </hr>   

## Code-Snippets

In [48]:
# This is the convention used to import Pandas.
import pandas as pd

In [49]:
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [50]:
# START YOUR CODE HERE.
df = pd.DataFrame(people)
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [51]:
df.columns # to see the columns in this dataframe

Index(['first', 'last', 'email'], dtype='object')

In [52]:
df.columns = ['first_name','last_name','email'] # i changed the columns name like that
print(df.columns)
df

Index(['first_name', 'last_name', 'email'], dtype='object')

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [53]:
df.columns = [x.upper() for x in df.columns] # to change column names with list comprehension
df

  FIRST_NAME LAST_NAME                    EMAIL
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [54]:
df.columns = df.columns.str.replace(' ','_') # i wanna replace the spaces in column names with underscore, so i use str.replace method
df # nothing change, because my column names have no spaces in their names
#if i do that
#df.columns = df.columns.str.replace('_',' ') # all underscores has been changed with spaces
#df

df.columns = [x.lower() for x in df.columns] # again lower case
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [55]:
df.rename(columns={'first_name':'first','last_name':'last'}, inplace=True) # if i want to change just some column names, i use the rename method and to save in same dataframe -> inplace = True
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [56]:
df.loc[2] = ['John','Smith','JohnSmith@email.com'] # I can change an information in a row like that
df

df.loc[2,['last','email']] = ['Doe','JohnDoe@email.com'] # if i want to change more than a column information but not all, i can use this technic
df

df.loc[2,'last'] = 'Smith' # if i wanna change just a value, i dont need a list
df

df.at[2,'last'] = 'Doe' # at method works to change value too
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [57]:
filt = (df['email'] == 'JohnDoe@email.com')
# df[filt]['last'] = 'Smith' # so i cant change the last name of the person who fit the filter. There are a lot panda operations on background which cause an error 
df.loc[filt,'last'] = 'Smith' # however that works
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John    Smith        JohnDoe@email.com

In [58]:
df['email'].str.lower() # i changed all columns values into lower case but the values in df hasn't been changed, to do this
df['email'] = df['email'].str.lower() # i have to write it like this way
df

   first     last                    email
0  Corey  Schafer  coreymschafer@gmail.com
1   Jane      Doe        janedoe@email.com
2   John    Smith        johndoe@email.com

In [59]:
# apply, map, applymap,replace methods

#apply method works either on dataframe or series object and apply it every values
df['email'].apply(len) # shows me the every emails length

def update_email(email): # a basic function to update emails into uppercase
    return email.upper()

df['email'].apply(update_email) # we dont need the pass the parameter in update_email function, aplly take this function and use for all email column values, but doesnt change the values in df 
df['email'] = df['email'].apply(update_email) # change the values in df
df

df['email'] = df['email'].apply(lambda x:x.lower()) # instead of a function i can use lambda function in apply method also
df

# apply in df 
df['email'].apply(len) # that how this method works with series(a vector in df)

df.apply(len) # that works with columns, show how many values have the each columns 

# len(df['email']) its the same what apply method does but with every column

df.apply(len, axis='columns') # show the lenght of every columns, how many values every values, horizontal,df.apply(len) vertical and default value for axis is rows

df.apply(pd.Series.min) # shows the minimum values every rows/series

df.apply(lambda x:x.min()) # its the same, lambda works in df with series

first                      Corey
last                         Doe
email    coreymschafer@gmail.com
dtype: object

In [60]:
# applymap only works with dataframe not with series
# apply take the series from dataframe and if i use it like this df.apply(len) but applymap works with every values in df
df.applymap(len) # shows a df and show every values length

df.applymap(str.lower) # makes all values in df lowercase

/tmp/ipykernel_63788/4124526828.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(len) # shows a df and show every values length
/tmp/ipykernel_63788/4124526828.py:5: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(str.lower) # makes all values in df lowercase

   first     last                    email
0  corey  schafer  coreymschafer@gmail.com
1   jane      doe        janedoe@email.com
2   john    smith        johndoe@email.com

In [61]:
#map method works with series(columns only), it changes the values of series. I can use dict or a function for that
df['first'].map({'Corey':'Chris','Jane':'Mary'}) # the values that i didnt change has been shown up as NaN

# if a use replace method those values arent replaced with NaN(John stays John)
df['first'].replace({'Corey':'Chris','Jane':'Mary'})

0    Chris
1     Mary
2     John
Name: first, dtype: object

<hr style="border:2px solid gray"> </hr>   
    
## Real-word Example

In [62]:
# These options help us to inspect our data more easily.
pd.set_option("display.max_columns", 85)
pd.set_option("display.max_rows", 85)

In [63]:
# These commands load the same survey data Corey is using in his video.
df = pd.read_csv("data/survey_results_public.csv", index_col = "Respondent")
schema_df = pd.read_csv("data/survey_results_schema.csv", index_col = "Column")

In [64]:
# START YOUR CODE HERE.
df.head(5)

df.rename(columns = {'ConvertedComp' : 'SalaryUSD'}, inplace=True) # Change the columnname ConvertedComp into SalaryUSD
df['SalaryUSD']

Respondent
1            NaN
2            NaN
3         8820.0
4        61000.0
5            NaN
          ...
88377        NaN
88601        NaN
88802        NaN
88816        NaN
88863        NaN
Name: SalaryUSD, Length: 88883, dtype: float64

In [65]:
df['Hobbyist']

Respondent
1        Yes
2         No
3        Yes
4         No
5        Yes
        ...
88377    Yes
88601     No
88802     No
88816     No
88863    Yes
Name: Hobbyist, Length: 88883, dtype: object

In [66]:
df['Hobbyist'] = df['Hobbyist'].map({'Yes':True,'No':False}) # change the yes values into true and no into false
df['Hobbyist']

Respondent
1         True
2        False
3         True
4        False
5         True
         ...
88377     True
88601    False
88802    False
88816    False
88863     True
Name: Hobbyist, Length: 88883, dtype: bool

<hr style="border:2px solid gray"> </hr>   
   
## Practice Tasks

In [67]:
# Load a clean DataFrame.
df = pd.read_csv("data/survey_results_public.csv", index_col = "Respondent")

#### 1. Adjust the DataFrame's column names so that every column name is lowercased. 
<br /> 
<details>    
<summary>
    <font size="3" color="red"><b>Hints (click to expand)</b></font>
</summary>
<p>
    <ul>
        <li>Make use of list comprehensions.</li>
        <li>The lower-method converts strings to lowercasing.</li> 
    </ul>
</p>
</details>

In [68]:
old_columns = df.columns
# YOUR CODE STARTS HERE.

df.columns = df.columns.str.lower()
df.columns = [x.lower() for x in df.columns]

#YOUR CODE ENDS HERE.

In [69]:
# THIS CELL TESTS YOUR RESULTS.
assert df.columns[0] == "mainbranch", "Your lowercasing does not seem to work!"
assert df.columns[-1] == "surveyease", "Your lowercasing does not seem to work!"

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Solution (click to expand)</b></font>
</summary>
<p>
    <code>df.columns = [column.lower() for column in df.columns]</code>
</p>
</details>

In [70]:
# For better readability, we undo this change. We applied it just for practice reasons. 
df.columns = old_columns

#### 2. Some column names are misleading. Rename the columns *CareerSat* and *MgrIdiot* to *CareerSatisfaction* and *ManagerAwareness*. 
<br />
<details>    
<summary>
    <font size="3" color="red"><b>Hints (click to expand)</b></font>
</summary>
<p>
    <ul>
        <li>One can use Pandas' rename-function to rename indexes/columns.</li>
        <li>How should you set the axis-argument inside the rename-functioncall?</li>
        <li>How should you set the inplace-parameter inside the rename-functioncall?</li>
    </ul>
</p>
</details>

In [71]:
# START YOUR CODE HERE.

df.rename(columns={"CareerSat": "CareerSatisfaction", "MgrIdiot": "ManagerAwareness"}, inplace=True)
# END YOUR CODE HERE.
df.columns

Index(['MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource', 'Employment',
       'Country', 'Student', 'EdLevel', 'UndergradMajor', 'EduOther',
       'OrgSize', 'DevType', 'YearsCode', 'Age1stCode', 'YearsCodePro',
       'CareerSatisfaction', 'JobSat', 'ManagerAwareness', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='object')

In [72]:
# THIS CELL TESTS YOUR RESULTS.
assert "CareerSatisfaction" in df.columns, "You did not rename CareerSat correctly!"
assert "ManagerAwareness" in df.columns, "You did not rename MgrIdiot correctly!"

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Solution (click to expand)</b></font>
</summary>
<p>
    <code>df.rename({"CareerSat": "CareerSatisfaction", "MgrIdiot": "ManagerAwareness"}, axis = "columns", inplace = True)</code>
</p>
</details>   
   
#### 3. For comparison reasons, we want to convert the current dollar salaries to euro salaries (*CompTotal* column). At that, we assume an exchange ratio of 85%. Therefore, one dollar should equal 85 cents. 
<br />
<details>    
<summary>
    <font size="3" color="red"><b>Hints (click to expand)</b></font>
</summary>
<p>
    <ul>
        <li>Which method should you use? Apply, applymap, or map?</li>
        <li>To be very efficient, you might want to solve this problem by using a lambda function inside the function call.</li>
        <li>CompTotal is of dtype float64. Therefore, arithmetics operations work as you would expect.</li> 
    </ul>
        
</p>
</details>

In [73]:
# START YOUR CODE HERE.

df["CompTotal"] = df['CompTotal'].apply(lambda x: x*85/100)

# END YOUR CODE HERE.

In [74]:
# THIS CELL TESTS YOUR RESULTS.
assert df["CompTotal"].loc[3] == 19550, "Your conversion does not seem to work properly!"
assert df["CompTotal"].loc[10] == 807500, "Your conversion does not seem to work properly!"
assert df["CompTotal"].loc[20] == 2550, "Your conversion does not seem to work properly!"

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Solution (click to expand)</b></font>
</summary>
<p>
    <code>df["CompTotal"] = df["CompTotal"].apply(lambda x: x*0.85)</code>
</p>
</details>

#### 4. In the *OpenSourcer* column, respondents were asked how often they contribute to open source projects. The answer options were: "Never," "Less than once per year," "Less than once a month but more than once per year," and "Once a month or more often." Complete the *adjust_OpenSourcer*-function so that it can be applied to the *OpenSourcer* column. The goal is for the new *OpenSourcer* column to contain False (boolean) if a respondent answered "Never". Otherwise, it should contain True (boolean). 
<br />
<details>    
<summary>
    <font size="3" color="red"><b>Hints (click to expand)</b></font>
</summary>
<p>
    <ul>
        <li>One can compare two values with the ==-operator.</li>
        <li>The original OpenSourcer column contains strings.</li>
        <li>Remind yourself of if/else conditionals.</li>
    </ul>
        
</p>
</details>

In [75]:
def adjust_OpenSourcer(answer):
    
    # START YOUR CODE HERE.
    if answer == 'Never':
        return False
    else:
        return True
    # END YOUR CODE HERE.
    
df["OpenSourcer"] = df["OpenSourcer"].apply(adjust_OpenSourcer)

In [76]:
# THIS CELL TESTS YOUR RESULTS.
assert df["OpenSourcer"].dtype == "bool", "adjust_OpenSourcer shall return boolean values!"
assert df["OpenSourcer"].iloc[0] == False, "Your adjustment seems to be incorrect!"
assert df["OpenSourcer"].iloc[-1] == True, "Your adjustment seems to be incorrect!"

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Solution (click to expand)</b></font>
</summary>
<p>
    <code>def adjust_OpenSourcer(answer):</code><br />
    <code>&nbsp;&nbsp;&nbsp;&nbsp;if answer == "Never":</code><br />
    <code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return False</code><br />
    <code>&nbsp;&nbsp;&nbsp;&nbsp;else:</code><br />
    <code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return True</code>
</p>
</details>

#### 5. Which method should you use if you want to adjust every value within a DataFrame?

applymap

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Solution (click to expand)</b></font>
</summary>
<p>
    applymap
</p>
</details>

#### 6. What is the main difference between *replace* and *map* as Series/DataFrame functions?

with map the values that i don't change is NaN but with replace is the unchanged value.

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Solution (click to expand)</b></font>
</summary>
<p>
    Map assigns NaN to each element that is not present in its mapper dictionary. Replace substitutes only the values that are present in its mapper dictionary, values that are not present remain unchanged. 
</p>
</details>